language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.2.7
  - DJANGO=1.3.7
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.1

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.2.7
    - python: "3.3"
      env: DJANGO=1.2.7
    - python: "3.4"
      env: DJANGO=1.2.7

    - python: "3.2"
      env: DJANGO=1.3.7
    - python: "3.3"
      env: DJANGO=1.3.7
    - python: "3.4"
      env: DJANGO=1.3.7

    - python: "3.2"
      env: DJANGO=1.4.10
    - python: "3.3"
      env: DJANGO=1.4.10
    - python: "3.4"
      env: DJANGO=1.4.10

before_script:
  - psql -c 'create database bitfield_test;' -U postgres

install:
  - pip install Django==$DJANGO
  - "if [[ $DJANGO == '1.2.7' ]]; then pip install psycopg2==2.4.1; fi"
  - "if [[ $DJANGO == '1.3.7' ]]; then pip install psycopg2==2.4.1; fi"
  - pip install -e .

script: python setup.py test
