language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.1

before_script:
  - psql -c 'create database bitfield_test;' -U postgres

install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install -e . --use-mirrors

script: python setup.py test

notifications:
  irc:
    channels: "irc.freenode.org#ahref"
    on_success: change
    on_failure: change
